function fig = rkwgui
% rkwgui steruje wykreslaniem paraboli o wprowadzonych z okna wspolczynnikach: a, b ,c
% rkwgui wyswietla rowniez informacje o miejscach zerowych i wierzcholku funkcji.
clear all;
global u1; % Zmienna w postaci wektora zawierajaca wspolczynniki a,b,c. 
           % u1(1)=a, u1(2)=b, u1(3)=c.
global u2; % Zmienna w postaci wektora zawierajaca wprowadzone wartosci Xmin, Xmax, Ymin, Ymax
           % u2(1)=Xmin, u2(2)=Xmax, u2(3)=Ymin, u2(4)=Ymax.
global h2; %identyfikator przycisku rysujacego w ustawionej skali
global h0; %identyfikator rysunku
% najstarsze okno
h0 = figure('Units','points', 'Position',[10 25 560 370], 'Resize','on', 'Tag','Fig1');
set(gcf,'NumberTitle','off',...
   'Name','Wykres paraboli w przedziale [-10:0.1:10] - MATLAB powyzej wersji 6.0');
h1 = uicontrol('Parent',h0, ...
   'Units','points', 'BackgroundColor',[0 0.7 0.5], 'Position',[0 350 560 15], ...
	'String','Funkcja rkwgui steruje wykreslaniem paraboli o zadanych wsp. a,b,c ', ...
	'Style','text', 'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[0 0.7 0.7], 'Position',[0 320 180 30], ...
	'String','Wprowadz wartosci a,b,c', ...
	'Style','text', 'Tag','StaticText2');
uicontrol('Parent',h0, ...
	'Units','points', 'ListboxTop',0, 'Position',[10 325 20 15], ...
	'String','a=', ...
	'Style','text', 'Tag','StaticText1');
u1(1) = uicontrol('Parent',h0, ...      %okno edycyjne do wprowadzenia wartosci 'a'
	'Units','points', ...
	'BackgroundColor',[1 1 1], 'ListboxTop',0,  'Position',[30 325 30 15], ...
   'String','','Style','edit', 'Tag','EditText1');
uicontrol('Parent',h0, ...
	'Units','points', 'ListboxTop',0, 'Position',[60 325 20 15], ...
	'String','b=', ...
	'Style','text', 'Tag','StaticText1');
u1(2) = uicontrol('Parent',h0, ...  %okno edycyjne do wprowadzenia wartosci 'b'
	'Units','points', 'BackgroundColor',[1 1 1], 'ListboxTop',0,  'Position',[80 325 30 15], ...
   'String','',   'Style','edit',   'Tag','EditText1');
uicontrol('Parent',h0, ...
	'Units','points', 'ListboxTop',0, 'Position',[110 325 20 15], ...
	'String','c=', ...
	'Style','text', 'Tag','StaticText1');
u1(3) = uicontrol('Parent',h0, ...  %okno edycyjne do wprowadzenia wartosci 'c'
	'Units','points', 'BackgroundColor',[1 1 1], 'ListboxTop',0, 'Position',[130 325 30 15], ...
   'String','', 'Style','edit',   'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...   % przycisk rysujacy w skali automatycznej
	'Units','points', 'Callback','rkwrys;', 'Position',[0 300 180 20], ...
   'String','               RYSOWANIE', ...
   'TooltipString','Rysuje parabole w przedziale X=[-2:0.01:2]',...
	'Style','pushbutton',  'Tag','Pushbutton1');
%  miejsca zerowe funkcji, oraz wspolrzedne wieszcholka
h3 = uicontrol('Parent',h0, ...   
	'Units','points', ...         %  miejsca zerowe funkcji, oraz wspolrzedne wieszcholka
   'Position',[180 335 120 15],  'BackgroundColor',[0 0.9 0.7], ...
   'TooltipString','Miejsca zerowe X1, X2 oraz wspolrzednych wierzcholka XW, YW',...
   'String','Wyniki',   'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',   'BackgroundColor',[0 0.9 0.7], 'Position',[180 300 60 35], ...
	'String',' miejsca zerowe', 'Style','text',  'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',   'BackgroundColor',[0 0.9 0.7], 'Position',[180 310 20 10], ...
	'String',' X1=', ...
	'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points', 'BackgroundColor',[1 1 1], 'Position',[200 310 38 10], ...
	'String','', 'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',   'BackgroundColor',[0 0.9 0.7], 'Position',[180 300 20 10], ...
	'String',' X2=', ...
	'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[1 1 1], 'Position',[200 300 38 10], ...
	'String','', 'Style','text',  'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points', 'BackgroundColor',[0 0.9 0.7], 'Position',[240 300 60 35], ...
	'String','wierzcholek ', 'Style','text',  'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[0 0.9 0.7], 'Position',[240 310 20 10], ...
	'String',' Xw=', 'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',   'BackgroundColor',[1 1 1], 'Position',[260 310 38 10], ...
	'String','', 'Style','text',   'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[0 0.9 0.7], 'Position',[240 300 20 10], ...
	'String',' Yw=', 'Style','text',  'Tag','StaticText2');
uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[1 1 1], 'Position',[260 300 38 10], ...
	'String','', 'Style','text',   'Tag','StaticText2');
h4 = uicontrol('Parent',h0, ...
	'Units','points', 'Callback','close;', 'Position',[430 5 100 20], ...
   'TooltipString','Zamyka okno i konczy prace programu',...
   'String','KONIEC', 'Style','pushbutton',  'Tag','Pushbutton1');
return
