function fig = rlcGUI
%interfejs graficzny do analizy rezonansu napiec
global Cs C vslider vedit rys
format compact
h0 = figure('Units','points', ...
	'Position',[10 25 560 370], ...
	'Resize','on', ...
   'Tag','Fig2');
set(gcf,'NumberTitle','off',...
   'Name','Analiza rezonansu napiec w obwodzie szeregowym RLC');
h1 = uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[0 0.7 0.5], ...
	'Position',[0 350 560 15], ...
	'String','SYMULACJA REZONANSU W OBWODZIE RLC poprzez zmiane pojemnosci Cs w F', ...
	'Style','text', ...
   'Tag','StaticText2');

uicontrol('Parent',h0, ...
   'Units','points', ...
   'BackgroundColor',[0 0.7 0.7], ...
	'Position',[0 320 560 30], ...
	'String','1 - suwakiem wybierz Cs, 2 - nacisnij OBLICZENIA, 3 - 1,2 az do uzyskania rezonansu  ', ...
	'Style','text', ...
   'Tag','StaticText2');
C=0.01;
vslider=uicontrol('style','slider',...
    'units','normalized',...
    'position',[.05,.084,.035,0.75],...
    'min',0.0015,'max',1.5,...
    'value',C,...
    'callback','rlcrys(2)');
 vedit=uicontrol('style','edit',...
    'units','normalized',...
    'position',[.01 .01 .10 .05],...
    'string',['Cs=',num2str(C)]);

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','rlcrys(1)', ...
	'Position',[50 300 250 20], ...
   'String','WPROWADZENIE DANYCH PODSTAWOWYCH', ...
	'Style','pushbutton', ...
   'Tag','Pushbutton1');
     rys = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','rlcrys(3)', ...
	'Position',[50 280 250 20], ...
   'String','OBLICZENIA ', ...
	'Enable','off',...
   'Style','pushbutton', ...
   'Tag','Pushbutton1');

uicontrol('Parent',h0, ...
   'Units','points',  'BackgroundColor',[1 1 1], 'Position',[260 300 38 10], ...
    'String','', 'Style','text',   'Tag','StaticText2');
h2 = uicontrol('Parent',h0, ...
    'Units','points', 'Callback','close;', 'Position',[430 5 100 20], ...
   'TooltipString','Zamyka okno i konczy prace programu',...
   'String','KONIEC', 'Style','pushbutton',  'Tag','Pushbutton1');
return

